# Generated by Django 3.2.13 on 2022-06-08 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_auteur', models.CharField(max_length=100)),
                ('prenom_auteur', models.CharField(max_length=100)),
                ('age_auteur', models.IntegerField(blank=True, null=True)),
                ('photo_auteur', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_jeux', models.CharField(max_length=100)),
                ('description_jeux', models.TextField(blank=True, null=True)),
                ('annee_sortie_jeux', models.DateField(blank=True, null=True)),
                ('editeur_jeux', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_jeux', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('auteur_jeux', models.ManyToManyField(to='application.auteurs')),
                ('categorie_jeux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_joueur', models.CharField(max_length=100)),
                ('prenom_joueur', models.CharField(max_length=100)),
                ('age_joueur', models.IntegerField(blank=True, null=True)),
                ('photo_joueur', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('jeux_joueur', models.ManyToManyField(to='application.Jeux')),
            ],
        ),
    ]
