# Generated by Django 3.2.13 on 2022-06-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteurs',
            name='photo_auteur',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
