# Generated by Django 3.2.13 on 2022-06-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auteurs_jeux_joueur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joueur',
            name='age_joueur',
        ),
        migrations.RemoveField(
            model_name='joueur',
            name='jeux_joueur',
        ),
        migrations.RemoveField(
            model_name='joueur',
            name='photo_joueur',
        ),
        migrations.AddField(
            model_name='joueur',
            name='mail_joueur',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='joueur',
            name='mdp_joueur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='auteur_jeux',
            field=models.ManyToManyField(to='application.Auteurs'),
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire_jeu', models.TextField(blank=True, null=True)),
                ('date_commentaire', models.DateField(blank=True, null=True)),
                ('note_commentaire', models.IntegerField(blank=True, null=True)),
                ('jeu_commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.jeux')),
                ('joueur_commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.joueur')),
            ],
        ),
    ]
