# Generated by Django 3.2.13 on 2022-06-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20220608_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_joueur', models.CharField(max_length=100)),
                ('prenom_joueur', models.CharField(max_length=100)),
                ('mail_joueur', models.EmailField(blank=True, max_length=254, null=True)),
                ('mdp_joueur', models.CharField(blank=True, max_length=100, null=True)),
                ('type_joueur', models.CharField(choices=[('PRO', 'PRO'), ('PARTICULIER', 'PARTICULIER')], default='PARTICULIER', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='decription_categorie',
            new_name='description_categorie',
        ),
        migrations.RenameField(
            model_name='jeux',
            old_name='annee_sortie_jeux',
            new_name='annee_sortie_jeu',
        ),
        migrations.RenameField(
            model_name='jeux',
            old_name='auteur_jeux',
            new_name='auteur_jeu',
        ),
        migrations.RenameField(
            model_name='jeux',
            old_name='categorie_jeux',
            new_name='categorie_jeu',
        ),
        migrations.RenameField(
            model_name='jeux',
            old_name='description_jeux',
            new_name='description_jeu',
        ),
        migrations.RenameField(
            model_name='jeux',
            old_name='editeur_jeux',
            new_name='editeur_jeu',
        ),
        migrations.RenameField(
            model_name='jeux',
            old_name='nom_jeux',
            new_name='nom_jeu',
        ),
        migrations.RenameField(
            model_name='jeux',
            old_name='photo_jeux',
            new_name='photo_jeu',
        ),
        migrations.AlterField(
            model_name='jeux',
            name='auteur_jeu',
            field=models.ManyToManyField(to='application.Auteurs'),
        ),
        migrations.AlterField(
            model_name='commentaires',
            name='joueur_commentaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.joueurs'),
        ),
        migrations.DeleteModel(
            name='Joueur',
        ),
    ]
