# Generated by Django 3.2.13 on 2022-06-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20220608_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteurs',
            name='photo_auteur',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='auteur_jeu',
            field=models.ManyToManyField(to='application.Auteurs'),
        ),
    ]
