# Generated by Django 3.2.13 on 2022-06-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_jeux_auteur_jeu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Categories',
        ),
        migrations.AlterField(
            model_name='jeux',
            name='auteur_jeu',
            field=models.ManyToManyField(to='application.Auteurs'),
        ),
    ]
