# Generated by Django 3.2.13 on 2022-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_jeux_auteur_jeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='auteur_jeu',
            field=models.ManyToManyField(to='application.Auteurs'),
        ),
    ]
